name = "SoilDifferentialEquations"
uuid = "65c8d809-e25b-4adf-9c1b-de173a457f19"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HydroTools = "179359cd-bac3-4aa1-bccd-287172463ab0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[weakdeps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[sources]
HydroTools = {url = "https://github.com/jl-pkgs/HydroTools.jl"}

[extensions]
SoilDiffEqExt = "OrdinaryDiffEq"

[compat]
Dates = "1.11.0"
HydroTools = "0.1.7"
Parameters = "0.12.3"
Printf = "1.11.0"
UnPack = "1.0.2"

[extras]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RTableTools = "76227a05-389e-44bd-84ad-996dde4b1834"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OrdinaryDiffEq", "RTableTools"]
