name = "SoilDifferentialEquations"
uuid = "65c8d809-e25b-4adf-9c1b-de173a457f19"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.4"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HydroTools = "179359cd-bac3-4aa1-bccd-287172463ab0"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[weakdeps]
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"

[sources]
HydroTools = {url = "https://github.com/jl-pkgs/HydroTools.jl"}

[extensions]
SoilDiffEqExt = "OrdinaryDiffEqTsit5"

[compat]
Dates = "1.11.0"
FFTW = "1.8.1"
HydroTools = "0.1.7"
HypergeometricFunctions = "0.3.27"
OffsetArrays = "1.15.0"
OrdinaryDiffEqTsit5 = "1.1.0"
Parameters = "0.12.3"
Printf = "1.11.0"
Reexport = "1.2.2"
StructArrays = "0.7.0"
UnPack = "1.0.2"

[extras]
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
RTableTools = "76227a05-389e-44bd-84ad-996dde4b1834"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OrdinaryDiffEqTsit5", "RTableTools"]
